blank_issues_enabled: false
contact_links:
  - name: Telegram Bot Support
    url: https://github.com/JonnerPaz/pokeshowdown_bot/discussions
    about: Ask questions, share feedback, or discuss features with the community.
